language: php

php:
  - 7.2
  - 7.3

sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - psql --version
  - psql -U postgres -c 'CREATE DATABASE yiitest;';
  - psql -U postgres yiitest < tests/data/pgsql.sql
  - echo "<?php unset(\$config['databases']['pgsql']['fixture']);" > tests/data/config.local.php

  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
